# Tutorial 01 – Working with Data

In this tutorial we will take a look at how to represent, manipulate, store, and load data. We will use two main packages called `NumPy` and `pandas`. The actual representation of data is handled by `NumPy` and it uses n-dimensional array objects to stored the data. Part of the code is written in C, C++, and Fortran to make it fast. `pandas` is high-level abstraction that makes data manipulation like selecting a specific subset of data, grouping, and basic plotting simple. Mastering just these two packages almost qualifies you as a data scientist.

While none of these two packages is really doing any machine learning you can go quite a long way with them. `NumPy` alone is perfect for any linear algebra like matrix multiplication and it is an essential requirement for other machine learning packages. `pandas` is great for exploring data and storing/loading data.

Remember, nicely prepared data are the key to success in machine learning.

## NumPy

`NumPy` is typically imported with alias `np` to save some characters.

In [17]:
import numpy as np

You can create a simple array right from a list.

In [18]:
alist = [1,2,3,4]
array = np.array(alist)
array

array([1, 2, 3, 4])

They behave quite similarly in terms of indexing and slicing. Doing any operations with arrays is quite different though. They behave more like vectors (which they are after all). The key difference is that it is a proper array and it cannot be easily extended with new elements.

In [19]:
print(array[1])
print(array[1::2])
print(array * 2)
print(array + 10)
print(array + array)
print(array * array)
# array.append(10) this does not work!

2
[2 4]
[2 4 6 8]
[11 12 13 14]
[2 4 6 8]
[ 1  4  9 16]


Notice that the math operations are done element-wise. Multiplying `array` with it self results in vector of squared elements. If you would like to do some linear algebra you need to call a method.

In [20]:
array.dot(array)

30

Now its time to go to higher dimensions.

In [21]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Multidimensional arrays can be also index in each dimension. 

In [22]:
matrix[1:, :2]

array([[4, 5],
       [7, 8]])

You can even use array of booleans to take elements on indices with value True.

In [23]:
matrix[[True, False, True]]

array([[1, 2, 3],
       [7, 8, 9]])

Often you will need to create larger arrays with some specific values and you would not want to manually fill all the numbers. Luckily, there are handful of methods at your disposal.

In [24]:
print(np.zeros(10))
print(np.full(3, fill_value=7))
print(np.identity(5))
print(np.eye(5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[7 7 7]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Now, every array has its shape, i.e., dimensions. They are always represented as tuples and each dimension is called axis.

In [25]:
print(array.shape)
print(np.identity(10).shape)

(4,)
(10, 10)


Note that when creating an array you can supply any wild shape you want the new array to have. That's right, you can make a tensor.

In [26]:
np.ones(shape=(3, 5, 7))

array([[[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]]])

Every array can be reshaped into any shape you like as long as the number of elements is equal to the product of array dimensions.

<div class="alert alert-block alert-warning"><b>Exercise 1</b></div>

Reshape the vector $\mathbf{a}$ into shape $(3,4,2)$, multiply it with matrix $\mathbf{M}$ and than flatten it back to vector. The expected result is $[ 11,  53,  95, 137, 179, 221, 263, 305, 347, 389, 431, 473]$.

In [27]:
M = np.arange(10, 12)
a = np.arange(24)
print(M)
print(a)

[10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [28]:
# TODO: your code goes here...
a = a.reshape((3, 4, 2))
print(a)
a=a@M
print(a)
a = a.reshape((1,1,12))
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[ 11  53  95 137]
 [179 221 263 305]
 [347 389 431 473]]
[[[ 11  53  95 137 179 221 263 305 347 389 431 473]]]


All these operations are incredibly fast. Below is a code that takes the matrix and normalizes the values, i.e., divides all values by maximal value in the matrix.

In [29]:
matrix = np.random.randint(0, 100, (1000, 1000))
%timeit -n 5 matrix / matrix.max()

3.5 ms ± 144 µs per loop (mean ± std. dev. of 7 runs, 5 loops each)


<div class="alert alert-block alert-warning"><b>Exercise 2</b></div>

Write a function that does the same thing with list of lists and compare the times.

In [64]:
def normalize(list_matrix):
    # TODO: your code goes here...
    x = max(map(max, list_matrix))
    for matrix in list_matrix:
        for m in matrix:
            m / x
    pass

In [65]:
list_matrix = matrix.tolist()
%timeit -n 5 normalize(list_matrix)

51.5 ms ± 2.44 ms per loop (mean ± std. dev. of 7 runs, 5 loops each)


<div class="alert alert-block alert-warning"><b>Exercise 3</b></div>

Later in the course we will use metrics to evaluate machine learning models. Write a function `rmse(x, y)` that computes one such metric called Root Mean Squared Error (RMSE) of two vectors $x$ and $y$ given by the following formula $$\text{RMSE} = \sqrt{\frac{\sum_{i=0}^{n}{(x_i-y_i)^2}}{n}}$$

The expected result for the predefined vectors is 2.16794833886788.

In [32]:
import math as math

x = np.array([0, 4, 1, 0, 2, 0, 2, 2, 4, 2])
y = np.array([1, 1, 2, 3, 1, 4, 1, 0, 3, 4])

def rmse(x, y):
    # TODO: your code goes here...
    tmp = 0
    for i in range(len(x)):
        tmp += math.pow(x[i] - y[i],2)
    print(math.sqrt(tmp/len(x)))
    pass

rmse(x,y)

2.16794833886788


<div class="alert alert-block alert-warning"><b>Exercise 4</b></div>

Typical operation in linear algebra you might encounter is a matrix multiplication. Let's say we measure three quantities (e.g. width, height, and depth of real life objects). For each observation we have a vector of these measurements $(w, h, d)$. Now suppose we need to transform these measurements for further processing such that each observation is transformed into $(w+h, h-d)$. We want to transform these observations at once using transformation matrix $\mathbf{M}$.
1. Stack observation into a matrix of observations $\mathbf{X}$ with each row corresponding to one of the observations, i.e. $\mathbf{X} = \begin{pmatrix}x_1 \\ x_2 \\ x_3 \\ x_4\end{pmatrix}$.
2. Write a transformation matrix $\mathbf{M}$ such that $\mathbf{X}\mathbf{M} = \mathbf{Y}$ where $\mathbf{Y}$ has transformed observations as rows. In other words, the following equations needs to hold.
$$\begin{pmatrix}1 & 4 & 6 \\ 2 & 4 & 7 \\ 1 & 2 & 8 \\ 1 & 4 & 9\end{pmatrix} \times \mathbf{M} = \begin{pmatrix}5 & -2 \\ 6 & -3 \\ 3 & -6 \\ 5 & -5 \end{pmatrix}$$

In [67]:
x1 = np.array([1, 4, 6])
x2 = np.array([2, 4, 7])
x3 = np.array([1, 2, 8])
x4 = np.array([1, 4, 9])

In [68]:
# TODO: your code goes here...
X = np.stack((x1, x2, x3, x4))
m1 = np.array([1, 0])
m2 = np.array([1, 1])
m3 = np.array([0, -1])
M = np.stack((m1, m2, m3))
print(M)
X@M

[[ 1  0]
 [ 1  1]
 [ 0 -1]]


array([[ 5, -2],
       [ 6, -3],
       [ 3, -6],
       [ 5, -5]])

<div class="alert alert-block alert-warning"><b>Exercise 5</b></div>

Matrix multiplication is also basis for projections that helps to reduce dimensionality of the data. One such projection is known as Principal Component Analysis (PCA) that we will cover in depth later. For now, let's say we have observation $\mathbf{x_1},\ldots,\mathbf{x_4}$ and we want to project them using PCA.
1. Stack observation vectors into a matrix $\mathbf{X}$.
2. Center each column of $\mathbf{X}$ by subtracting its mean. We lable the centered matrix $\mathbf{X_c}$.
3. Compute $\mathbf{C_X}$ which is a covariation matrix of $\mathbf{X^T}$, i.e., transposed matrix $\mathbf{X}$.
4. Computer projected observations $\mathbf{Y}$ given by the formula
$$\mathbf{Y} = \mathbf{X_c}\mathbf{P}$$
where $\mathbf{P}$ is a matrix of eigenvectors of $\mathbf{C_X}$.

Expected result for the given observations is $$Y = \begin{pmatrix}  \phantom{-}0.61750836 & \phantom{-}0.10599488 & -0.02394807 & 0. \\ -0.48025785 & -0.12818168 & -0.03235508 & 0. \\ \phantom{-}0.22710374 & -0.20107790 & \phantom{-}0.03341513 & 0. \\ -0.36435424 & \phantom{-}0.22326470 & \phantom{-}0.02288802 &  0. \end{pmatrix}$$

In [69]:
x1 = np.array([1, 1, 1, 1])
x2 = np.array([1, 0.5, 0.9, 0])
x3 = np.array([1, 1, 1, 0.5])
x4 = np.array([1, 0.3, 1, 0.3])
X = np.stack((x1,x2,x3,x4))
print(X)

[[1.  1.  1.  1. ]
 [1.  0.5 0.9 0. ]
 [1.  1.  1.  0.5]
 [1.  0.3 1.  0.3]]


In [36]:
# TODO: your code goes here...
from numpy import linalg as LA
def center(matrix):
    l = []
    for i in range(1, len(matrix) + 1):
        l = np.append(l, np.mean(matrix[0:,(i-1):i]))
    return np.subtract(X, np.array(l))
Xc = center(X)
Cx = np.cov(X.transpose())
w, P = LA.eig(Cx)
Y = Xc.dot(P)
Y

array([[ 0.61750836,  0.10599488, -0.02394807,  0.        ],
       [-0.48025785, -0.12818168, -0.03235508,  0.        ],
       [ 0.22710374, -0.2010779 ,  0.03341513,  0.        ],
       [-0.36435424,  0.2232647 ,  0.02288802,  0.        ]])

## Pandas

`Pandas` is usually imported with alias `pd` to save some characters.

In [37]:
import pandas as pd

The main feature of `Pandas` is a data structure called `DataFrame`. You can think of it as a table with named columns and number rows. Let's create some data frames.

In [38]:
df = pd.DataFrame([[10, "hey", 0.3], [20, "hi", 0.1],[30, "hello", 0.16]], columns=["number", "greeting", "ratio"], index=["first", "second", "third"])
df

number greeting  ratio
first       10      hey   0.30
second      20       hi   0.10
third       30    hello   0.16

You can also specify data column-wise. Both styles produce the same result.

In [39]:
pd.DataFrame({"number": [10, 20, 30], "greeting": ["hey", "hi", "hello"], "ratio": [0.3, 0.1, 0.16]}, index=["first", "second", "third"])

number greeting  ratio
first       10      hey   0.30
second      20       hi   0.10
third       30    hello   0.16

You can select a sub-table both by names of columns/rows or by their indices. The data are actually saved as `Numpy` array so you can use the same indexing techniques.

In [40]:
df["number"]

first     10
second    20
third     30
Name: number, dtype: int64

In [41]:
df[["number", "ratio"]]

number  ratio
first       10   0.30
second      20   0.10
third       30   0.16

In [42]:
df.loc["first"]

number       10
greeting    hey
ratio       0.3
Name: first, dtype: object

In [43]:
df.loc[["first", "third"]]

number greeting  ratio
first      10      hey   0.30
third      30    hello   0.16

In [44]:
df.loc[["first", "third"], ["greeting"]]

greeting
first      hey
third    hello

In [45]:
df.iloc[1:, :2]

number greeting
second      20       hi
third       30    hello

You can also query the data frame and get rows that satisfy a defined condition. This can be done either by supplying binary index vector (the first example) or explicitly calling `query` method (the second example).

In [46]:
df[(df.number >= 20) & (df.greeting.str.contains('e'))]

number greeting  ratio
third      30    hello   0.16

In [47]:
df.query('number > (ratio * 100)')

number greeting  ratio
second      20       hi   0.10
third       30    hello   0.16

`Pandas` also implements all the basic statistics you might need to know about data.

In [48]:
df.describe()

number     ratio
count     3.0  3.000000
mean     20.0  0.186667
std      10.0  0.102632
min      10.0  0.100000
25%      15.0  0.130000
50%      20.0  0.160000
75%      25.0  0.230000
max      30.0  0.300000

In [49]:
df['number'].median()

20.0

Apart from manipulating data in memory, it is also handy for loading and storing data on disk. It implements many standard file formats like `csv`, `hdf`, and `pickle`. Saving and loading a file is as easy as calling a single method.

In [50]:
df.to_csv('example.csv')

In [51]:
pd.read_csv("example.csv")

Unnamed: 0  number greeting  ratio
0      first      10      hey   0.30
1     second      20       hi   0.10
2      third      30    hello   0.16

Notice that the process of saving and loading the same file does not necessarily result in the identical data frame. In this example, the index of original data frame has become a column. In this very example we need to specify column that will be used as index. This, however, is not a universal solution, you might encounter many problems.

In [52]:
pd.read_csv("example.csv", index_col=0)

number greeting  ratio
first       10      hey   0.30
second      20       hi   0.10
third       30    hello   0.16

You can even specify an URL of file you would like to read.

In [53]:
weather = pd.read_csv("https://www.fi.muni.cz/~xcechak1/IB031/datasets/weather.csv")
weather

outlook  temperature  humidity  windy play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        86  False  yes
3      rainy           70        96  False  yes
4      rainy           68        80  False  yes
5      rainy           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13     rainy           71        91   True   no

<div class="alert alert-block alert-warning"><b>Exercise 6</b></div>

Let's do some "data science"! Compute a mean temperature of days when golf was played. The expected result is 73.0.

In [72]:
# TODO: your code goes here...
weather[weather.play == 'yes'].temperature.mean()

73.0

<div class="alert alert-block alert-warning"><b>Exercise 7</b></div>

Compute the most common weather outlook when golf was not played. The expected result is sunny.

In [73]:
# TODO: your code goes here...
weather[weather.play == 'no'].outlook.mode()

0    sunny
dtype: object

It is really easy to modify and calculate with whole columns. You can also save the result as new column. Notice that you can access columns either like values in dictionaries but also as attributes.

In [56]:
weather['humidity'] + weather.temperature

0     170
1     170
2     169
3     166
4     148
5     135
6     129
7     167
8     139
9     155
10    145
11    162
12    156
13    162
dtype: int64

In [57]:
weather['over_70'] = weather.temperature > 70
weather

outlook  temperature  humidity  windy play  over_70
0      sunny           85        85  False   no     True
1      sunny           80        90   True   no     True
2   overcast           83        86  False  yes     True
3      rainy           70        96  False  yes    False
4      rainy           68        80  False  yes    False
5      rainy           65        70   True   no    False
6   overcast           64        65   True  yes    False
7      sunny           72        95  False   no     True
8      sunny           69        70  False  yes    False
9      rainy           75        80  False  yes     True
10     sunny           75        70   True  yes     True
11  overcast           72        90   True  yes     True
12  overcast           81        75  False  yes     True
13     rainy           71        91   True   no     True

<div class="alert alert-block alert-warning"><b>Exercise 8</b></div>

Compute the correlation between columns `windy` and `play`. The expected result is -0.258199.

In [58]:
# TODO: your code goes here...
weather['play_bool'] = weather.play == "yes"
weather[['windy', 'play_bool']].corr()

windy  play_bool
windy      1.000000  -0.258199
play_bool -0.258199   1.000000

Until now, we just took the data as is and computed something on on it or its subset. Sometimes this is not enough and we need to rearrange the data a bit. There are three common operations: grouping, pivoting, and melting. Grouping is useful if you want to aggregate information base on value in a specified column(s). Pivot and melt operations reshapes the data frame. You might need these operations to reshape the data frame for easier plotting.

In [59]:
weather[['outlook', 'humidity']].groupby('outlook').mean()

humidity
outlook           
overcast      79.0
rainy         83.4
sunny         82.0

The function applied to the groups can be arbitrary, e.g., take the last row with the given value.

In [60]:
weather.groupby('outlook').apply(lambda group: group.iloc[-1])

outlook  temperature  humidity  windy play  over_70  play_bool
outlook                                                                  
overcast  overcast           81        75  False  yes     True       True
rainy        rainy           71        91   True   no     True      False
sunny        sunny           75        70   True  yes     True       True

In [74]:
melted_df = weather.melt(id_vars='play', value_vars=['windy', 'outlook', 'over_70'])
melted_df

play variable     value
0    no    windy     False
1    no    windy      True
2   yes    windy     False
3   yes    windy     False
4   yes    windy     False
5    no    windy      True
6   yes    windy      True
7    no    windy     False
8   yes    windy     False
9   yes    windy     False
10  yes    windy      True
11  yes    windy      True
12  yes    windy     False
13   no    windy      True
14   no  outlook     sunny
15   no  outlook     sunny
16  yes  outlook  overcast
17  yes  outlook     rainy
18  yes  outlook     rainy
19   no  outlook     rainy
20  yes  outlook  overcast
21   no  outlook     sunny
22  yes  outlook     sunny
23  yes  outlook     rainy
24  yes  outlook     sunny
25  yes  outlook  overcast
26  yes  outlook  overcast
27   no  outlook     rainy
28   no  over_70      True
29   no  over_70      True
30  yes  over_70      True
31  yes  over_70     False
32  yes  over_70     False
33   no  over_70     False
34  yes  over_70     False
35   no  over_70      True
36  yes  over_70     False
37  yes  over_70      True
38  yes  over_70      True
39  yes  over_70      True
40  yes  over_70      True
41   no  over_70      True

In [62]:
weather[:5].pivot(index='windy', columns='temperature', values=['play'])

play                    
temperature   68   70   80   83   85
windy                               
False        yes  yes  NaN  yes   no
True         NaN  NaN   no  NaN  NaN

<div class="alert alert-block alert-danger"><b>Exercise 9</b></div>

Download and load dataset `attempts.csv` from https://github.com/adaptive-learning/adaptive-learning-research/tree/master/data/robomission-2019-12. Read the instructions on the page and briefly read through data description.

1. Find id of the student with the most solved problems. Expected result is 16364.
2. Compute average success rate of problems. Expected results starts with 0.870189, 0.973117, 0.866077, 0.362319, 0.658576.
3. Add 2 minutes to all time stamps in column `start`.
4. Create a table with row for each student and column for each item. The value on row $i$ and column $j$ says whether student $j$ have ever solved problem $j$.

In [103]:
# TODO: your code goes here...
attempts = pd.read_csv("attempts.csv")
print(attempts.head())
attempts.groupby('student').apply(lambda g: g.solved.sum()).idxmax()
attempts.groupby('item').mean()['solved']
attempts['start'] = pd.to_datetime(attempts['start']) + pd.Timedelta('2 minutes')

has_solved = attempts.groupby(['student', 'item']).apply(lambda g: any(g.solved))
has_solved.reset_index().rename(columns = {0: 'solved'}).pivot(index='student', columns='item', values=['solved']).fillna(False)

   id  event_order  student  item                             start  \
0   4            1       29     2  2017-11-10 12:20:05.152265+00:00   
1   5            2       29    12  2017-11-10 12:20:32.155447+00:00   
2   6            3       29    10  2017-11-10 12:20:54.080259+00:00   
3   7            4       29    14  2017-11-10 12:21:06.966330+00:00   
4   8            5       29    11  2017-11-10 12:21:33.061485+00:00   

                                        item_setting item_solution item_order  \
0  {'toolbox': ['fly'], 'fields': 'b|bM|b|bM|b;kM...           lrf  (1, 2, 4)   
1  {'toolbox': ['fly', 'shoot'], 'fields': 'b|b|b...          rrff  (2, 2, 1)   
2  {'toolbox': ['fly', 'shoot'], 'fields': 'b|bA|...           fsf  (2, 1, 1)   
3  {'toolbox': ['fly'], 'fields': 'bM|b|bD|b|b;k|...           frl  (1, 3, 2)   
4  {'toolbox': ['fly', 'shoot', 'repeat'], 'lengt...        R4{fs}  (3, 1, 1)   

   solved      time  response_time_sec  executions  edits program  
0    True  3.17805

solved                                                                 \
item        1      2      3      4      5      6      7      8      9      10   
student                                                                         
5        False  False  False  False  False  False  False  False  False  False   
29        True   True   True  False  False  False  False   True  False   True   
584      False   True   True  False  False   True  False   True  False  False   
769      False  False  False  False  False  False  False  False  False  False   
909      False  False  False  False  False  False  False  False  False  False   
...        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
18487    False   True   True  False  False  False  False   True  False   True   
18488    False  False  False  False  False  False  False  False  False  False   
18489    False  False  False  False  False  False  False  False  False  False   
18491     True  False   True  False  False  False  False   True  False   True   
18494    False   True  False  False  False  False  False   True  False  False   

         ...                                                                 \
item     ...     77     78     79     80     81     82     83     84     85   
student  ...                                                                  
5        ...  False  False  False  False  False  False  False  False  False   
29       ...  False  False  False  False  False  False  False  False  False   
584      ...  False  False  False  False  False  False  False  False  False   
769      ...  False  False  False  False  False  False  False  False  False   
909      ...  False  False  False  False  False  False  False  False  False   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
18487    ...  False  False   True  False  False  False  False   True  False   
18488    ...  False  False  False  False  False  False  False  False  False   
18489    ...  False  False  False  False  False  False  False  False  False   
18491    ...  False  False  False  False  False  False  False   True  False   
18494    ...  False  False  False  False  False  False  False  False  False   

                
item        86  
student         
5        False  
29       False  
584      False  
769      False  
909      False  
...        ...  
18487     True  
18488    False  
18489    False  
18491     True  
18494    False  

[8527 rows x 85 columns]